name: workflow 1 run on commit
on:
  push:
    branches:
      - main
  
jobs:
  build:
    name: run workflow 1
    runs-on: ubuntu-latest
    steps:
      - name: Discord notifications
        uses: cl8dep/action-discord@52da597599bc7e2076b16b8a3c12a7a1d54f6b47
          
